/** Generated by scripts/prepareConstitutionFs.js. Do not edit. */
// constitution-fs-authority-json:{"supported":true,"schemaVersion":1,"protocolVersion":2,"platform":"darwin","arch":"arm64","fileName":"wayland-constitution-fs","sha256":"sha256:7b6985898c658708d595578b16d59a4995ae82f7d0cf2e880cdcd4a6f208af83","size":714448}
export const PACKAGED_CONSTITUTION_FS_AUTHORITY = {
  "supported": true,
  "schemaVersion": 1,
  "protocolVersion": 2,
  "platform": "darwin",
  "arch": "arm64",
  "fileName": "wayland-constitution-fs",
  "sha256": "sha256:7b6985898c658708d595578b16d59a4995ae82f7d0cf2e880cdcd4a6f208af83",
  "size": 714448
} as const;
