/** Generated by scripts/prepareConstitutionFs.js. Do not edit. */
// constitution-fs-authority-json:{"supported":true,"schemaVersion":1,"protocolVersion":2,"platform":"darwin","arch":"arm64","fileName":"wayland-constitution-fs","sha256":"sha256:10d123cc1cc83fbdfa6e430d9580108f70fb17a141909c2a3ef79ccd10b69f71","size":714448}
export const PACKAGED_CONSTITUTION_FS_AUTHORITY = {
  supported: true,
  schemaVersion: 1,
  protocolVersion: 2,
  platform: 'darwin',
  arch: 'arm64',
  fileName: 'wayland-constitution-fs',
  sha256: 'sha256:10d123cc1cc83fbdfa6e430d9580108f70fb17a141909c2a3ef79ccd10b69f71',
  size: 714448,
} as const;
