/** Generated by scripts/prepareConstitutionFs.js. Do not edit. */
// constitution-fs-authority-json:{"supported":true,"schemaVersion":1,"protocolVersion":2,"platform":"darwin","arch":"arm64","fileName":"wayland-constitution-fs","sha256":"sha256:ee1b07e0ed26113511f39f209f8bcb4d8efd5f56db2047b48e240dcc4ee165f3","size":714448}
export const PACKAGED_CONSTITUTION_FS_AUTHORITY = {
  "supported": true,
  "schemaVersion": 1,
  "protocolVersion": 2,
  "platform": "darwin",
  "arch": "arm64",
  "fileName": "wayland-constitution-fs",
  "sha256": "sha256:ee1b07e0ed26113511f39f209f8bcb4d8efd5f56db2047b48e240dcc4ee165f3",
  "size": 714448
} as const;
