#!/usr/bin/env node

'use strict';

const { execFileSync } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const GENERATED = path.join(ROOT, 'src', 'process', 'services', 'constitution', 'constitutionFsAuthority.generated.ts');

function writeGenerated(authority, generatedPath = GENERATED) {
  fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
  fs.writeFileSync(
    generatedPath,
    `/** Generated by scripts/prepareConstitutionFs.js. Do not edit. */\n` +
      `// constitution-fs-authority-json:${JSON.stringify(authority)}\n` +
      `export const PACKAGED_CONSTITUTION_FS_AUTHORITY = ${JSON.stringify(authority, null, 2)} as const;\n`
  );
}

function prepareConstitutionFs(options = {}) {
  const platform = options.platform || process.env.CONSTITUTION_FS_TARGET_PLATFORM || process.platform;
  const arch = options.arch || process.env.CONSTITUTION_FS_TARGET_ARCH || process.arch;
  const root = options.root || ROOT;
  const manifest = options.manifest || path.join(root, 'native', 'constitution-fs', 'Cargo.toml');
  const outputRoot = options.outputRoot || path.join(root, 'resources', 'bundled-constitution-fs');
  const generated =
    options.generated ||
    path.join(root, 'src', 'process', 'services', 'constitution', 'constitutionFsAuthority.generated.ts');
  const execute = options.execFileSync || execFileSync;
  const prebuiltBinary = options.prebuiltBinary;
  const supportedPlatform = platform === 'darwin' || platform === 'linux';

  fs.rmSync(outputRoot, { recursive: true, force: true });
  if (!supportedPlatform) {
    writeGenerated({ supported: false, platform, arch, protocolVersion: 2 }, generated);
    console.log(`[constitution-fs] ${platform}-${arch} is explicitly unsupported; no helper staged`);
    return { supported: false, platform, arch };
  }
  if (platform !== process.platform || arch !== process.arch) {
    throw new Error(
      `[constitution-fs] cannot compile supported target ${platform}-${arch} on ${process.platform}-${process.arch}; use an exact-target build runner`
    );
  }

  if (!prebuiltBinary) {
    execute('cargo', ['build', '--locked', '--release', '--manifest-path', manifest], {
      cwd: root,
      env: process.env,
      stdio: 'inherit',
    });
  }

  const fileName = 'wayland-constitution-fs';
  const source = prebuiltBinary || path.join(root, 'native', 'constitution-fs', 'target', 'release', fileName);
  const sourceStat = fs.lstatSync(source);
  if (!sourceStat.isFile() || sourceStat.isSymbolicLink()) {
    throw new Error('[constitution-fs] prebuilt helper must be one regular non-symlink file');
  }
  const destinationRoot = path.join(outputRoot, `${platform}-${arch}`);
  const destination = path.join(destinationRoot, fileName);
  fs.mkdirSync(destinationRoot, { recursive: true, mode: 0o700 });
  fs.copyFileSync(source, destination);
  fs.chmodSync(destination, 0o755);

  if (platform === 'darwin') {
    const identity = process.env.WAYLAND_CONSTITUTION_FS_SIGN_IDENTITY || '-';
    execute('/usr/bin/codesign', ['--force', '--sign', identity, '--timestamp=none', destination], {
      stdio: 'inherit',
    });
    execute('/usr/bin/codesign', ['--verify', '--strict', destination], { stdio: 'inherit' });
  }

  const bytes = fs.readFileSync(destination);
  const sha256 = `sha256:${crypto.createHash('sha256').update(bytes).digest('hex')}`;
  const authority = {
    supported: true,
    schemaVersion: 1,
    protocolVersion: 2,
    platform,
    arch,
    fileName,
    sha256,
    size: bytes.byteLength,
  };
  fs.writeFileSync(
    path.join(destinationRoot, 'manifest.json'),
    `${JSON.stringify(
      {
        schemaVersion: 1,
        protocolVersion: 2,
        platform,
        arch,
        binary: { fileName, sha256, size: bytes.byteLength },
      },
      null,
      2
    )}\n`
  );
  writeGenerated(authority, generated);
  console.log(`[constitution-fs] staged ${platform}-${arch} ${sha256}`);
  return authority;
}

module.exports = prepareConstitutionFs;

if (require.main === module) {
  prepareConstitutionFs({ prebuiltBinary: process.env.CONSTITUTION_FS_PREBUILT_BINARY || undefined });
}
