// GENERATED by gen_error_table (cargo run -p nano-cli --bin gen_error_table) — do not edit.
// Source of truth: crates/nano-session/src/error_codes.rs (wayland-nano repo).

export type NanoErrorKind =
  | 'model_auth'
  | 'model_rate_limited'
  | 'model_context_overflow'
  | 'compaction_failed'
  | 'model_entitlement'
  | 'model_server_5xx'
  | 'model_server_4xx'
  | 'model_transport'
  | 'model_protocol'
  | 'model_output_schema'
  | 'model_unsupported_param'
  | 'egress_denied'
  | 'fs_read_denied'
  | 'fs_write_denied'
  | 'fs_sensitive_denied'
  | 'fs_io'
  | 'fs_edit'
  | 'shell_spawn'
  | 'sandbox_unavailable'
  | 'sandbox_setup'
  | 'mcp_server'
  | 'mcp_protocol'
  | 'mcp_output_bounded'
  | 'mcp_transport'
  | 'mcp_timeout'
  | 'mcp_resource_unsupported'
  | 'mcp_resource_denied'
  | 'mcp_content_unsupported'
  | 'mcp_elicitation_unsupported'
  | 'mcp_authorization_required'
  | 'mcp_credstore_unavailable'
  | 'mcp_oauth_failed'
  | 'unknown_tool'
  | 'missing_args'
  | 'approval_denied'
  | 'hook_blocked'
  | 'pty_session_gone'
  | 'review_parse_failed'
  | 'shell_rule_denied'
  | 'rule_file_invalid'
  | 'budget_exhausted'
  | 'budget_exceeded'
  | 'no_progress'
  | 'repeat_force_stop'
  | 'user_cancelled'
  | 'journal_unavailable'
  | 'session_not_found'
  | 'session_busy'
  | 'model_not_found'
  | 'turn_in_progress'
  | 'no_session'
  | 'invalid_params'
  | 'session_fork_failed'
  | 'goal_op_failed'
  | 'model_lacks_vision'
  | 'model_lacks_pdf'
  | 'image_invalid'
  | 'image_unsupported_format'
  | 'image_too_large'
  | 'image_too_many'
  | 'attachment_missing'
  | 'attachment_store_error'
  | 'checkpoint_unavailable'
  | 'checkpoint_not_found'
  | 'checkpoint_restore_failed'
  | 'cua_policy_denied'
  | 'cua_focus_lost'
  | 'cua_os_permission_denied'
  | 'cua_backend_unavailable'
  | 'cua_coordinate_out_of_range'
  | 'cua_backend'
  | 'carrier_missing'
  | 'carrier_oversized'
  | 'malformed_json'
  | 'duplicate_key'
  | 'noncanonical_payload'
  | 'unknown_field'
  | 'unsupported_schema'
  | 'unsupported_algorithm'
  | 'invalid_key_encoding'
  | 'invalid_signature_encoding'
  | 'invalid_signature'
  | 'unknown_issuer'
  | 'revoked_issuer'
  | 'unknown_key'
  | 'revoked_key'
  | 'key_not_yet_valid'
  | 'key_expired'
  | 'assertion_not_yet_valid'
  | 'assertion_expired'
  | 'clock_out_of_bounds'
  | 'nonce_replay'
  | 'idempotency_conflict'
  | 'unknown_product_subject'
  | 'retired_product_subject'
  | 'principal_mismatch'
  | 'principal_remap'
  | 'retired_identifier_reuse'
  | 'unauthorized_project'
  | 'authority_widening'
  | 'artifact_mismatch'
  | 'resume_fingerprint_missing'
  | 'resume_drift'
  | 'fallback_unauthorized'
  | 'continuity_not_enabled'
  | 'control_unauthorized'
  | 'control_race_lost'
  | 'authority_store_unavailable'
  | 'ambiguous_recovery';

export type NanoErrorSurface = 'error_response' | 'tool_card' | 'stop_reason';

export interface NanoErrorSpec {
  kind: NanoErrorKind;
  surface: NanoErrorSurface;
  wireCode: number;
  retryable: boolean;
  title: string;
  hint: string;
}

export const NANO_ERROR_SPECS: readonly NanoErrorSpec[] = [
  {
    kind: 'model_auth',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Authentication failed',
    hint: "Check the provider's API key, then retry",
  },
  {
    kind: 'model_rate_limited',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Rate limited',
    hint: 'Retrying automatically; wait a moment',
  },
  {
    kind: 'model_context_overflow',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Context too long',
    hint: 'Start a new session or /compact',
  },
  {
    kind: 'compaction_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Context compaction failed',
    hint: 'Start a new session',
  },
  {
    kind: 'model_entitlement',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Model not entitled',
    hint: 'Switch model or check plan',
  },
  {
    kind: 'model_server_5xx',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Provider server error (5xx)',
    hint: 'Transient; retry',
  },
  {
    kind: 'model_server_4xx',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Provider rejected the request (4xx)',
    hint: 'Check model and account',
  },
  {
    kind: 'model_transport',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Network error reaching provider',
    hint: 'Check connectivity, then retry',
  },
  {
    kind: 'model_protocol',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Malformed provider stream',
    hint: 'Report; not retryable',
  },
  {
    kind: 'model_output_schema',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Structured output rejected',
    hint: 'Loosen the schema or retry without it',
  },
  {
    kind: 'model_unsupported_param',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Parameter unsupported on this model',
    hint: 'Clear the named setting, then retry',
  },
  {
    kind: 'egress_denied',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Blocked by egress policy',
    hint: 'Report this — a Flux-policy trip is a bug',
  },
  {
    kind: 'fs_read_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_write_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_sensitive_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_io',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'File operation failed',
    hint: '',
  },
  {
    kind: 'fs_edit',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Edit matched 0 or ambiguous ranges',
    hint: 'Re-read the file',
  },
  {
    kind: 'shell_spawn',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandboxed launch failed',
    hint: '',
  },
  {
    kind: 'sandbox_unavailable',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandbox unavailable — command not run (fail-closed)',
    hint: '',
  },
  {
    kind: 'sandbox_setup',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandbox setup failed',
    hint: '',
  },
  {
    kind: 'mcp_server',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server reported an error',
    hint: '',
  },
  {
    kind: 'mcp_protocol',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server sent a malformed response',
    hint: '',
  },
  {
    kind: 'mcp_output_bounded',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server output exceeded the bound',
    hint: '',
  },
  {
    kind: 'mcp_transport',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: true,
    title: 'MCP server unreachable',
    hint: '',
  },
  {
    kind: 'mcp_timeout',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: true,
    title: 'MCP server timed out',
    hint: '',
  },
  {
    kind: 'mcp_resource_unsupported',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "This MCP server doesn't expose resources.",
    hint: '',
  },
  {
    kind: 'mcp_resource_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "That resource URI wasn't advertised by the server; list resources first.",
    hint: '',
  },
  {
    kind: 'mcp_content_unsupported',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "Binary resource content isn't supported yet.",
    hint: '',
  },
  {
    kind: 'mcp_elicitation_unsupported',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "This MCP server needs a question flow Nano doesn't support on this transport.",
    hint: '',
  },
  {
    kind: 'mcp_authorization_required',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Login required: nano auth login <server>.',
    hint: '',
  },
  {
    kind: 'mcp_credstore_unavailable',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Secure credential storage is unavailable; provision <VAR>_FILE (0600) or fix the keyring.',
    hint: '',
  },
  {
    kind: 'mcp_oauth_failed',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'OAuth login failed (<bounded reason>).',
    hint: '',
  },
  {
    kind: 'unknown_tool',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Unknown tool',
    hint: '',
  },
  {
    kind: 'missing_args',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Bad tool arguments',
    hint: '',
  },
  {
    kind: 'approval_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by user',
    hint: '',
  },
  {
    kind: 'hook_blocked',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Blocked by lifecycle hook',
    hint: '',
  },
  {
    kind: 'pty_session_gone',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'That terminal session has exited',
    hint: '',
  },
  {
    kind: 'review_parse_failed',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "The review finished but its report couldn't be parsed",
    hint: '',
  },
  {
    kind: 'shell_rule_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by a shell rule',
    hint: 'The saved rules.toml denies this command; edit or remove the rule',
  },
  {
    kind: 'rule_file_invalid',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Shell rules file is invalid or insecurely configured; running with no saved rules',
    hint: 'Fix or remove rules.toml (strict TOML, owner-only permissions)',
  },
  {
    kind: 'budget_exhausted',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: budget exhausted',
    hint: 'Start a new session or narrow the task',
  },
  {
    kind: 'budget_exceeded',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Session token budget exceeded',
    hint: '/budget continue <tokens> grants more, or start a new session',
  },
  {
    kind: 'no_progress',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: no observable progress',
    hint: 'Rephrase or narrow the task',
  },
  {
    kind: 'repeat_force_stop',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: repeated identical tool call',
    hint: 'Redirect the model with a new instruction',
  },
  {
    kind: 'user_cancelled',
    surface: 'stop_reason',
    wireCode: 0,
    retryable: false,
    title: 'Cancelled',
    hint: '',
  },
  {
    kind: 'journal_unavailable',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Session storage unavailable',
    hint: 'Check disk and permissions; do not retry blindly',
  },
  {
    kind: 'session_not_found',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Session not found',
    hint: '',
  },
  {
    kind: 'session_busy',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Session is open in another host',
    hint: 'Close it there (or resume after that host exits), then retry',
  },
  {
    kind: 'model_not_found',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Model not available',
    hint: 'Pick a model from the advertised catalog',
  },
  {
    kind: 'turn_in_progress',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'A turn is already running',
    hint: 'Wait for it or cancel it first',
  },
  {
    kind: 'no_session',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'No session',
    hint: 'Call session/new first',
  },
  {
    kind: 'invalid_params',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Invalid request parameters',
    hint: '',
  },
  {
    kind: 'session_fork_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Session fork failed',
    hint: 'Check the session id; retry when no turn is running',
  },
  {
    kind: 'goal_op_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Goal operation failed',
    hint: 'Check goal status, then retry',
  },
  {
    kind: 'model_lacks_vision',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: "This model can't process images",
    hint: 'Switch to a vision-capable model (/model)',
  },
  {
    kind: 'model_lacks_pdf',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Selected model wire cannot carry PDF documents',
    hint: 'Select an advertised Flux Anthropic Messages leaf, then retry',
  },
  {
    kind: 'image_invalid',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: "The image couldn't be read",
    hint: 'Corrupt or not really an image',
  },
  {
    kind: 'image_unsupported_format',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: "That image format isn't supported",
    hint: 'Convert to PNG or JPEG and retry',
  },
  {
    kind: 'image_too_large',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'The image is too large',
    hint: 'Limit: 50 MiB file / 768 KiB after compression',
  },
  {
    kind: 'image_too_many',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Too many images in one prompt',
    hint: 'Limit: 16 images',
  },
  {
    kind: 'attachment_missing',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: "An earlier attachment couldn't be restored from the attachment store",
    hint: '',
  },
  {
    kind: 'attachment_store_error',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'The attachment store is unavailable or insecurely configured',
    hint: '',
  },
  {
    kind: 'checkpoint_unavailable',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Workspace checkpoints are unavailable',
    hint: 'Check system Git, checkpoint storage permissions, and store contention',
  },
  {
    kind: 'checkpoint_not_found',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Checkpoint not found',
    hint: 'It may have been evicted by checkpoint retention',
  },
  {
    kind: 'checkpoint_restore_failed',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Checkpoint restore did not complete',
    hint: 'Resume the session to run checkpoint recovery',
  },
  {
    kind: 'cua_policy_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Computer-use policy denied the operation',
    hint: 'Re-screenshot and re-plan; the policy will deny this again',
  },
  {
    kind: 'cua_focus_lost',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'The focused window changed before the action was dispatched',
    hint: 'Re-screenshot and re-target the now-focused window',
  },
  {
    kind: 'cua_os_permission_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'The OS computer-use permission is not granted',
    hint: 'Grant the permission in the OS settings, then retry',
  },
  {
    kind: 'cua_backend_unavailable',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Computer use is unavailable on this desktop session',
    hint: 'No usable display backend; do not retry',
  },
  {
    kind: 'cua_coordinate_out_of_range',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Coordinates are outside the primary display',
    hint: 'Re-screenshot and target coordinates inside the display bounds',
  },
  {
    kind: 'cua_backend',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'The computer-use backend failed',
    hint: 'Do not retry the identical action',
  },
  {
    kind: 'carrier_missing',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'carrier_missing',
  },
  {
    kind: 'carrier_oversized',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'carrier_oversized',
  },
  {
    kind: 'malformed_json',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'malformed_json',
  },
  {
    kind: 'duplicate_key',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'duplicate_key',
  },
  {
    kind: 'noncanonical_payload',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'noncanonical_payload',
  },
  {
    kind: 'unknown_field',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unknown_field',
  },
  {
    kind: 'unsupported_schema',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unsupported_schema',
  },
  {
    kind: 'unsupported_algorithm',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unsupported_algorithm',
  },
  {
    kind: 'invalid_key_encoding',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'invalid_key_encoding',
  },
  {
    kind: 'invalid_signature_encoding',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'invalid_signature_encoding',
  },
  {
    kind: 'invalid_signature',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'invalid_signature',
  },
  {
    kind: 'unknown_issuer',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unknown_issuer',
  },
  {
    kind: 'revoked_issuer',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'revoked_issuer',
  },
  {
    kind: 'unknown_key',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unknown_key',
  },
  {
    kind: 'revoked_key',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'revoked_key',
  },
  {
    kind: 'key_not_yet_valid',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'key_not_yet_valid',
  },
  {
    kind: 'key_expired',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'key_expired',
  },
  {
    kind: 'assertion_not_yet_valid',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'assertion_not_yet_valid',
  },
  {
    kind: 'assertion_expired',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'assertion_expired',
  },
  {
    kind: 'clock_out_of_bounds',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'clock_out_of_bounds',
  },
  {
    kind: 'nonce_replay',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'nonce_replay',
  },
  {
    kind: 'idempotency_conflict',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'idempotency_conflict',
  },
  {
    kind: 'unknown_product_subject',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unknown_product_subject',
  },
  {
    kind: 'retired_product_subject',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'retired_product_subject',
  },
  {
    kind: 'principal_mismatch',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'principal_mismatch',
  },
  {
    kind: 'principal_remap',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'principal_remap',
  },
  {
    kind: 'retired_identifier_reuse',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'retired_identifier_reuse',
  },
  {
    kind: 'unauthorized_project',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'unauthorized_project',
  },
  {
    kind: 'authority_widening',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'authority_widening',
  },
  {
    kind: 'artifact_mismatch',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'artifact_mismatch',
  },
  {
    kind: 'resume_fingerprint_missing',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'resume_fingerprint_missing',
  },
  {
    kind: 'resume_drift',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'resume_drift',
  },
  {
    kind: 'fallback_unauthorized',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'fallback_unauthorized',
  },
  {
    kind: 'continuity_not_enabled',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'continuity_not_enabled',
  },
  {
    kind: 'control_unauthorized',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'control_unauthorized',
  },
  {
    kind: 'control_race_lost',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'control_race_lost',
  },
  {
    kind: 'authority_store_unavailable',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'authority_store_unavailable',
  },
  {
    kind: 'ambiguous_recovery',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Activation refused',
    hint: 'ambiguous_recovery',
  },
];

export const NANO_ERROR_BY_KIND: Readonly<Record<string, NanoErrorSpec>> = Object.fromEntries(
  NANO_ERROR_SPECS.map((s) => [s.kind, s])
);
