// GENERATED by gen_error_table (cargo run -p nano-cli --bin gen_error_table) — do not edit.
// Source of truth: crates/nano-session/src/error_codes.rs (wayland-nano repo).

export type NanoErrorKind =
  | 'model_auth'
  | 'model_rate_limited'
  | 'model_context_overflow'
  | 'compaction_failed'
  | 'model_entitlement'
  | 'model_server_5xx'
  | 'model_server_4xx'
  | 'model_transport'
  | 'model_protocol'
  | 'model_output_schema'
  | 'model_unsupported_param'
  | 'egress_denied'
  | 'fs_read_denied'
  | 'fs_write_denied'
  | 'fs_sensitive_denied'
  | 'fs_io'
  | 'fs_edit'
  | 'shell_spawn'
  | 'sandbox_unavailable'
  | 'sandbox_setup'
  | 'mcp_server'
  | 'mcp_protocol'
  | 'mcp_output_bounded'
  | 'mcp_transport'
  | 'mcp_timeout'
  | 'unknown_tool'
  | 'missing_args'
  | 'approval_denied'
  | 'budget_exhausted'
  | 'no_progress'
  | 'repeat_force_stop'
  | 'user_cancelled'
  | 'journal_unavailable'
  | 'session_not_found'
  | 'model_not_found'
  | 'turn_in_progress'
  | 'no_session'
  | 'invalid_params'
  | 'session_fork_failed'
  | 'goal_op_failed';

export type NanoErrorSurface = 'error_response' | 'tool_card' | 'stop_reason';

export interface NanoErrorSpec {
  kind: NanoErrorKind;
  surface: NanoErrorSurface;
  wireCode: number;
  retryable: boolean;
  title: string;
  hint: string;
}

export const NANO_ERROR_SPECS: readonly NanoErrorSpec[] = [
  {
    kind: 'model_auth',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Authentication failed',
    hint: 'Check FLUX_API_KEY, then retry',
  },
  {
    kind: 'model_rate_limited',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Rate limited',
    hint: 'Retrying automatically; wait a moment',
  },
  {
    kind: 'model_context_overflow',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Context too long',
    hint: 'Start a new session or /compact',
  },
  {
    kind: 'compaction_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Context compaction failed',
    hint: 'Start a new session',
  },
  {
    kind: 'model_entitlement',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Model not entitled',
    hint: 'Switch model or check plan',
  },
  {
    kind: 'model_server_5xx',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Provider server error (5xx)',
    hint: 'Transient; retry',
  },
  {
    kind: 'model_server_4xx',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Provider rejected the request (4xx)',
    hint: 'Check model and account',
  },
  {
    kind: 'model_transport',
    surface: 'error_response',
    wireCode: -32603,
    retryable: true,
    title: 'Network error reaching provider',
    hint: 'Check connectivity, then retry',
  },
  {
    kind: 'model_protocol',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Malformed provider stream',
    hint: 'Report; not retryable',
  },
  {
    kind: 'model_output_schema',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Structured output rejected',
    hint: 'Loosen the schema or retry without it',
  },
  {
    kind: 'model_unsupported_param',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Parameter unsupported on this model',
    hint: 'Clear the named setting, then retry',
  },
  {
    kind: 'egress_denied',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Blocked by egress policy',
    hint: 'Report this — a Flux-policy trip is a bug',
  },
  {
    kind: 'fs_read_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_write_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_sensitive_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by policy',
    hint: 'Path is outside the allowed set; ask the user',
  },
  {
    kind: 'fs_io',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'File operation failed',
    hint: '',
  },
  {
    kind: 'fs_edit',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Edit matched 0 or ambiguous ranges',
    hint: 'Re-read the file',
  },
  {
    kind: 'shell_spawn',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandboxed launch failed',
    hint: '',
  },
  {
    kind: 'sandbox_unavailable',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandbox unavailable — command not run (fail-closed)',
    hint: '',
  },
  {
    kind: 'sandbox_setup',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Sandbox setup failed',
    hint: '',
  },
  {
    kind: 'mcp_server',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server reported an error',
    hint: '',
  },
  {
    kind: 'mcp_protocol',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server sent a malformed response',
    hint: '',
  },
  {
    kind: 'mcp_output_bounded',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'MCP server output exceeded the bound',
    hint: '',
  },
  {
    kind: 'mcp_transport',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: true,
    title: 'MCP server unreachable',
    hint: '',
  },
  {
    kind: 'mcp_timeout',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: true,
    title: 'MCP server timed out',
    hint: '',
  },
  {
    kind: 'unknown_tool',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Unknown tool',
    hint: '',
  },
  {
    kind: 'missing_args',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Bad tool arguments',
    hint: '',
  },
  {
    kind: 'approval_denied',
    surface: 'tool_card',
    wireCode: -32603,
    retryable: false,
    title: 'Denied by user',
    hint: '',
  },
  {
    kind: 'budget_exhausted',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: budget exhausted',
    hint: 'Start a new session or narrow the task',
  },
  {
    kind: 'no_progress',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: no observable progress',
    hint: 'Rephrase or narrow the task',
  },
  {
    kind: 'repeat_force_stop',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Turn stopped: repeated identical tool call',
    hint: 'Redirect the model with a new instruction',
  },
  {
    kind: 'user_cancelled',
    surface: 'stop_reason',
    wireCode: 0,
    retryable: false,
    title: 'Cancelled',
    hint: '',
  },
  {
    kind: 'journal_unavailable',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Session storage unavailable',
    hint: 'Check disk and permissions; do not retry blindly',
  },
  {
    kind: 'session_not_found',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Session not found',
    hint: '',
  },
  {
    kind: 'model_not_found',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Model not available',
    hint: 'Pick a model from the advertised catalog',
  },
  {
    kind: 'turn_in_progress',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'A turn is already running',
    hint: 'Wait for it or cancel it first',
  },
  {
    kind: 'no_session',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'No session',
    hint: 'Call session/new first',
  },
  {
    kind: 'invalid_params',
    surface: 'error_response',
    wireCode: -32602,
    retryable: false,
    title: 'Invalid request parameters',
    hint: '',
  },
  {
    kind: 'session_fork_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Session fork failed',
    hint: 'Check the session id; retry when no turn is running',
  },
  {
    kind: 'goal_op_failed',
    surface: 'error_response',
    wireCode: -32603,
    retryable: false,
    title: 'Goal operation failed',
    hint: 'Check goal status, then retry',
  },
];

export const NANO_ERROR_BY_KIND: Readonly<Record<string, NanoErrorSpec>> = Object.fromEntries(
  NANO_ERROR_SPECS.map((s) => [s.kind, s])
);
