/**
 * @license
 * Copyright 2026 Ferrox Labs
 * SPDX-License-Identifier: Apache-2.0
 *
 * WHAT THE SHIPPED SMART TRADER PERSONA IS ALLOWED TO SAY.
 *
 * -------------------------------------------------------------------------
 * READ THIS BEFORE TRUSTING ANY ASSERTION IN THIS FILE.
 * -------------------------------------------------------------------------
 * Every test here is a CORPUS ASSERTION. It proves a sentence is present in a
 * document the model is given, and it proves nothing whatsoever about whether
 * the model obeys it. A document is advice, not an enforced invariant.
 *
 * For the save claim (C1.2) the enforcement exists and lives elsewhere:
 * `savedFileClaims.ts` plus `onChatTurnCompleted` compare what the model said
 * against what is actually on disk at the end of every turn, and
 * `tests/unit/artifacts/chatTurnClaimReconciliation.test.ts` is the test with
 * teeth. The clause asserted here exists so that the model and the host agree,
 * NOT so that the host can be dispensed with.
 *
 * For the watchlist source (C3) there is no enforcement and none can be built
 * in this lane - confining what a CHAT may read is a containment change far
 * larger than this, deferred as D4. This is doctrine, labelled as doctrine.
 *
 * -------------------------------------------------------------------------
 * WHY B6/B7 IS A DOCUMENT PROBLEM AND NOT A MODEL PROBLEM.
 * -------------------------------------------------------------------------
 * The engine log shows `ToolSearch: {"query":"tvcontrol-setup"}` returning
 * `No deferred tools matching "tvcontrol-setup" found`. The model looked for a
 * SKILL in the TOOL registry, got a miss, and invented "Settings -> Skills &
 * Tools" - a page that says, in the product, "You don't switch skills on and
 * off." The skill had been copied into its workspace one second earlier. The
 * document told it to "read that skill" without ever saying where the skill IS
 * or that a tool-registry miss means nothing.
 */

import { existsSync, readFileSync } from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';

const REPO_ROOT = path.resolve(__dirname, '../..');
const SMART_TRADER = path.join(REPO_ROOT, 'src/process/resources/assistant/smart-trader/smart-trader.md');
const SKILLS_DIR = path.join(REPO_ROOT, 'src/process/resources/skills');
const CONNECTOR_SCHEMA = path.join(REPO_ROOT, 'tests/fixtures/tvcontrol-2.3.1-tools.json');

const markdown = readFileSync(SMART_TRADER, 'utf-8');

/**
 * The 105 tools a REAL connector handshake reported.
 *
 * Generated by `scripts/gen-tvcontrol-schema-fixture.mjs` from a real stdio
 * `initialize` + `tools/list` against the installed bin shim - not a literal
 * list typed into this file, which would only prove that its author can type.
 */
const connectorTools = JSON.parse(readFileSync(CONNECTOR_SCHEMA, 'utf-8')) as {
  _header: { version: string; toolCount: number };
  tools: Record<string, unknown>;
};

/** Does a skill of this name ship in the bundle? */
const skillExists = (name: string): boolean => existsSync(path.join(SKILLS_DIR, name));

/**
 * Every skill the persona names.
 *
 * Read off the document rather than listed here: an inline-code token that
 * happens to be the name of a shipped skill directory IS a skill reference, and
 * a skill added to the persona tomorrow is covered without editing this file.
 */
function skillsNamedInPersona(): string[] {
  const names = new Set<string>();
  for (const match of markdown.matchAll(/`([a-z][a-z0-9]*(?:-[a-z0-9]+)+)`/g)) {
    if (skillExists(match[1])) names.add(match[1]);
  }
  return [...names].sort();
}

describe('C2/B6+B7 - the persona never sends anyone somewhere that does not exist', () => {
  it('CONTROL: the resolver can find a skill, and can say no', () => {
    // Without this, a resolver that answered "not found" for everything would
    // pass every assertion below.
    expect(skillExists('market-open-report')).toBe(true);
    expect(skillExists('tvcontrol-setup')).toBe(true);
    expect(skillExists('a-skill-that-does-not-ship')).toBe(false);
  });

  it('CONTROL: the persona really does name skills', () => {
    const named = skillsNamedInPersona();
    expect(named).toContain('market-open-report');
    expect(named).toContain('tvcontrol-setup');
  });

  it('names no Settings page at all', () => {
    // B6: "tell them to turn it on in Settings -> Skills & Tools - that is the
    // whole fix", on a page that states "You don't switch skills on and off".
    // A skill missing from a workspace is a workspace fact, not a toggle.
    expect(markdown).not.toMatch(/Settings\s*(?:→|->|>)/);
    expect(markdown).not.toMatch(/Skills\s*&\s*Tools/);
  });

  it('gives a workspace path for every skill it names', () => {
    const missing = skillsNamedInPersona().filter(
      (name) => !markdown.includes(`.wayland-core/skills/${name}`)
    );
    // "Read that skill" with no path is what sent the model to the tool
    // registry in the first place.
    expect(missing).toEqual([]);
  });

  it('says a skill is a file in the workspace and that a tool search cannot find one', () => {
    // B7's root cause, stated so the model does not have to infer it.
    // Whitespace-collapsed: the document hard-wraps at 100 columns and a
    // sentence being present must not depend on where the line broke.
    const flowing = markdown.replace(/\s+/g, ' ');
    expect(flowing).toMatch(/a skill is never in the tool registry/i);
    expect(flowing).toMatch(/that miss means nothing at all/i);
    expect(markdown).toMatch(/FILE IN YOUR WORKSPACE/);
  });
});

describe('C1.2 - the persona is told not to claim a file it did not write', () => {
  it('CORPUS ASSERTION ONLY: the clause is present', () => {
    // The enforcement is savedFileClaims.ts + onChatTurnCompleted. This proves
    // the sentence exists and NOTHING MORE.
    const flowing = markdown.replace(/\s+/g, ' ');
    expect(flowing).toMatch(/never say you saved a file unless a tool call in \*\*this turn\*\* wrote it/i);
    expect(flowing).toMatch(/say plainly that you did not save it/i);
  });
});

describe('C3/B8 - a watchlist question is answered from TradingView, and says so', () => {
  it('CONTROL: the connector fixture is the real 105-tool handshake', () => {
    expect(connectorTools._header.version).toBe('2.3.1');
    expect(Object.keys(connectorTools.tools)).toHaveLength(connectorTools._header.toolCount);
    expect(connectorTools._header.toolCount).toBe(105);
  });

  it('CORPUS ASSERTION ONLY: the source-of-truth clause is present', () => {
    // `grep -n watchlist_get smart-trader.md` returned nothing before this.
    const flowing = markdown.replace(/\s+/g, ' ');
    expect(markdown).toMatch(/`watchlist_get`/);
    expect(flowing).toMatch(/answered from `watchlist_get` and from nothing else/i);
  });

  it('describes the shipped CSV as the scanner INPUT, not the user list', () => {
    const flowing = markdown.replace(/\s+/g, ' ');
    expect(markdown).toMatch(/TC-MASTER-WATCHLIST\.csv/);
    expect(flowing).toMatch(/\*\*scanner.s input\*\*, not the user.s list/i);
  });

  it('requires the answer to name its source, and to age a cached one', () => {
    const flowing = markdown.replace(/\s+/g, ' ');
    expect(flowing).toMatch(/name the source in the answer/i);
    expect(flowing).toMatch(/say when the file was last modified/i);
  });

  it('every connector tool the persona names really exists in the shipped connector', () => {
    // A doctrine sentence naming a tool that does not exist is worse than no
    // sentence: it sends the model looking for something it cannot call.
    const named = [...markdown.matchAll(/`([a-z][a-z0-9]*(?:_[a-z0-9]+)+)`/g)].map((match) => match[1]);
    const connectorish = named.filter((name) => /^(watchlist|quote|chart|tv|data|draw|pine|alert|indicator)_/.test(name));
    expect(connectorish.length).toBeGreaterThan(0);
    const unknown = connectorish.filter((name) => !(name in connectorTools.tools));
    expect(unknown).toEqual([]);
  });
});
